//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace escuela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class actividades
    {
        public int idactividades { get; set; }
        public string nombreActividad { get; set; }
        public string bimestre { get; set; }
        public int C_profesoridprofesor { get; set; }
    
        public virtual profesor profesor { get; set; }
    }
}
