//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace escuela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asistencia
    {
        public int idasistencia { get; set; }
        public int grupo_idgrupo { get; set; }
        public int curso_idcurso { get; set; }
    
        public virtual curso curso { get; set; }
        public virtual grupo grupo { get; set; }
    }
}
