//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace escuela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public curso()
        {
            this.asistencia = new HashSet<asistencia>();
            this.calificaciones = new HashSet<calificaciones>();
        }
    
        public int idcurso { get; set; }
        public int profesor_idprofesor { get; set; }
        public int alumnos_idalumnos { get; set; }
        public int asignatura_idasignatura { get; set; }
        public int grupo_idgrupo { get; set; }
    
        public virtual alumnos alumnos { get; set; }
        public virtual asignatura asignatura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asistencia> asistencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calificaciones> calificaciones { get; set; }
        public virtual grupo grupo { get; set; }
        public virtual profesor profesor { get; set; }
    }
}
